### ISSUE TITLE
Add form event hooks

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#210]
This should be special behavior on certain event triggers, like:
1. on_create
2. on_delete
3. on_update
4. ~on_duplicate~
5. on_read[_one]
6. on_sign

Special event hooks like onApproval / onDisapproval will make more sense to implement using the approval process, see #62 and #39.

**Comment by signebedi** [comment]
We should also support a handful of built-in event triggers, like `sendMail ( subj, content, to_addr )` or `setAttr ( form_name, form_id, field, value )`.

**Comment by signebedi** [comment]
Implement `send_mail` built in event hook behavior
This will look something like:

```yaml
send_mail:
  template: form_created
  method: static
  target: bob@hr.example.com
```

Where the template points to one of the template names in the email config, method is an enum of ['static', 'group', and 'relationship'], and target is the value used to select the emails to send, based on the method. So, the example above will always send Bob a form_created email to bob@hr.example.com when a form is submitted. But, if we wanted to send this to all members of the `default` group, we could do the following:

```yaml
send_mail:
  template: form_created
  method: group
  target: default
```

**Comment by signebedi** [comment]
Implement `set_value` built in event hook behavior
This will look something like:

```yaml
set_value:
  selector_method: from_field
  value_method: static
  form_name: leave_requests
  field_name:  approval_status
  document_id: request_id
  value: "approved"
```




```yaml
set_value:
  selector_method: from_field
  value_method: from_field
  form_name: leave_requests
  field_name:  approver
  document_id: request_id
  value: __metadata__created_by
```

**Comment by signebedi** [comment]
Add a `__config__` param to forms to contain form-level params
This allows us to set form-level parameters, like a `form_label`, `summary_fields`, and/or `enable_title_field`. (#286) It also enables us to configure event triggers. We can also add a `presubmit_message` popup this way, add a `require_password`, and `allow_csv_uploads`.

**Comment by signebedi** [comment]
RelationshipType reciprocal_name should be nullable but unique if set
When we are trying to aggregate people by relationships, that means we  often need to be able to query on reciprocal_name ... as such, it should be unique.

**Comment by signebedi** [comment]
Implement `create_submission` built in event hook behavior
This will look something like:

```yaml
create_submission:
  form_name: example_form
  values:
    field_name_1:
      method: static
      value: "This text will always be the same"
    field_name_2:
      method: from_field
      value: some_field_name
    field_name_3:
      method: from_field
      value: __metadata__some_metadata_field
```

This will create an `example_form` form submission with the values set in the `values` dict. Should we support setting metadata fields too, just using the `__metadata__` field name prefix in the `values` dict keys?
