### ISSUE TITLE
Implement `send_mail` built in event hook behavior

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#313]
> This will look something like:

```yaml
send_mail:
  template: form_created
  method: static
  target: bob@hr.example.com
```

> Where the template points to one of the template names in the email config, method is an enum of ['static', 'group', and 'relationship'], and target is the value used to select the emails to send, based on the method. So, the example above will always send Bob a form_created email to bob@hr.example.com when a form is submitted. But, if we wanted to send this to all members of the `default` group, we could do the following:

```yaml
send_mail:
  template: form_created
  method: group
  target: default
```

_Originally posted by @signebedi in https://github.com/signebedi/libreforms-fastapi/issues/210#issuecomment-2211812137_

**Comment by signebedi** [comment]
I think the format will need to change slightly, along the lines of:

```yaml
on_create:
  - type: send_mail
    template: form_created
    method: static
    target: bob@hr.example.com
```

This will ensure we create a list of dicts. 

ALSO: static target should split and trim on commas, so we can send to multiple people with one entry.
