### ISSUE TITLE
Implement `set_value` built in event hook behavior

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#314]
> This will look something like:

```yaml
set_value:
  selector_method: from_field
  value_method: static
  target_form_name: leave_requests
  target_field_name:  approval_status
  target_document_id: request_id
  value: "approved"
```

> This logic is a little more complex, because we need to choose methods for two things: first, how to select the submission to assign the value to; second, how to select the value to assign to that submission. For this, we create selector_method and value_method, respectively. These are enums of ['static', 'from_field']. If selector_method is assigned "static", then target_document_id should be a assigned an actual document ID like 664eab5c46c99199a7b22ab7. If it is assigned "from_field", then target_document_id should be assigned a field that exists in the form that has just triggered the event handler - which should contain a document_id value.

> Likewise, if value_method is set to "static", then value is expected to be a static value; but, if value_method is set to "from_form", then value should correspond to a form field in the form that has just triggered the event handler, see example below.

```yaml
set_value:
  selector_method: from_field
  value_method: from_field
  target_form_name: leave_requests
  target_field_name:  approver
  target_document_id: request_id
  value: __metadata__created_by
```

> target_form_name and target_field_name should be static values.

_Originally posted by @signebedi in https://github.com/signebedi/libreforms-fastapi/issues/210#issuecomment-2211813700_
