### ISSUE TITLE
Add form_stage instruction validation

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#333]
> We've settled on using the following rules to specify form stages:
```yaml
form_name:
  __config__:
    form_stages:
      initial_stage:
        label: some stage name
        action: approval
        initial_stage: true
        required: true
        method: group
        target: group_name
        on_approve: send_to_some_stage_name
        on_deny: send_to_some_stage_name
        on_pushback: send_to_some_stage_name
```
> Some of these can have default behavior (like required); most fields will need to be specified in order for the logic to work; some will need to have their types validated; others still will need to have their values validated: for example, on_approve, on_deny, and on_pushback all need to point to another, valid stage within the same form config...

_Originally posted by @signebedi in https://github.com/signebedi/libreforms-fastapi/issues/62#issuecomment-2308523096_
