### ISSUE TITLE
Implement `create_submission` built in event hook behavior

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#342]
> This will look something like:

```yaml
create_submission:
  form_name: example_form
  values:
    field_name_1:
      method: static
      value: "This text will always be the same"
    field_name_2:
      method: from_field
      value: some_field_name
    field_name_3:
      method: from_field
      value: __metadata__some_metadata_field
```

> This will create an `example_form` form submission with the values set in the `values` dict. Should we support setting metadata fields too, just using the `__metadata__` field name prefix in the `values` dict keys?

_Originally posted by @signebedi in https://github.com/signebedi/libreforms-fastapi/issues/210#issuecomment-2327055595_
