### ISSUE TITLE
Implement `http_request` built in event hook behavior

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#373]
> This will look something like:

```yaml
- type: http_request
  target: https://api.jira.com/api/v1/create/
  method: post
  headers:
    X-API-KEY:
      value_method: static
      value: laksjdfhkjasdhfwj2317-sas-d
  body:
    request_type:
      value_method: from_form
      value: request_type
    description:
      value_method: jinja2
      value: "This is the description of a {{request_type}} submitted by {{__metadata__created_by}}"
```

> This will submit an http request to the designated target and include the relevant headers and body passed by the system.  You also need to specify the HTTP method (get, post, patch, put, delete) for the request. There are three ways to pass data: static, from_form, and jinja2. Jinja2 will allow you to embed values from within the form itself into a jinja2 string.

_Originally posted by @signebedi in https://github.com/signebedi/libreforms-fastapi/issues/210#issuecomment-2457827137_
