### ISSUE TITLE
Add support for conditional field display based on static equivalencies

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreforms-fastapi#379]
We should just support static equivalencies for now.

```yaml
field_name:
  conditional_display:
    enabled: true # default to false
    condition_field: some_field_name
    condition_value: lorem ipsum dolor sit amet
```

In the future, we will add an additional set of controls to allow operators and dynamic field comparisons.

```yaml
field_name:
  conditional_display:
    enabled: true # default to false
    condition_field: some_field_name
    condition_type: static # one of static or field, where field compares value of field_name with the value of condition_value, where that value is assumed to be a field name
    condition_operator: > # one of <, >, ==, !=, >=, or <=
    condition_value: lorem ipsum dolor sit amet
```
